### ISSUE TITLE
some error at minimal_working_example.ipynb

### ISSUE THREAD

**Issue by cgh2797** [maxime-langevin/scaffold-constrained-generation#1]
![캡처1aaaaa](https://user-images.githubusercontent.com/19909579/94381962-02392400-0176-11eb-93f6-721842fb81ae.PNG)

i run minial_working_example.ipynb

error message says, there's no "re"

it may be problem at "utils.py" ??

what should i do??

**Comment by cgh2797** [comment]
-solved-

original regex code is in REINVENT(original code)/data_structs.py

add import re

**Comment by maxime-langevin** [comment]
Thanks for pointing this out! I will commit the necessary change :) glad that you managed to solve the issue
